//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class i2psam_stream_settings : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal i2psam_stream_settings(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(i2psam_stream_settings obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~i2psam_stream_settings() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          i2psamPINVOKE.delete_i2psam_stream_settings(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string samhost {
    set {
      i2psamPINVOKE.i2psam_stream_settings_samhost_set(swigCPtr, value);
    } 
    get {
      string ret = i2psamPINVOKE.i2psam_stream_settings_samhost_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint16_t samport {
    get {
      SWIGTYPE_p_uint16_t ret = new SWIGTYPE_p_uint16_t(i2psamPINVOKE.i2psam_stream_settings_samport_get(swigCPtr), true);
      return ret;
    } 
  }

  public string nickname {
    set {
      i2psamPINVOKE.i2psam_stream_settings_nickname_set(swigCPtr, value);
    } 
    get {
      string ret = i2psamPINVOKE.i2psam_stream_settings_nickname_get(swigCPtr);
      return ret;
    } 
  }

  public string i2cp_opts {
    set {
      i2psamPINVOKE.i2psam_stream_settings_i2cp_opts_set(swigCPtr, value);
    } 
    get {
      string ret = i2psamPINVOKE.i2psam_stream_settings_i2cp_opts_get(swigCPtr);
      return ret;
    } 
  }

  public string destination {
    set {
      i2psamPINVOKE.i2psam_stream_settings_destination_set(swigCPtr, value);
    } 
    get {
      string ret = i2psamPINVOKE.i2psam_stream_settings_destination_get(swigCPtr);
      return ret;
    } 
  }

  public i2psam_stream_settings() : this(i2psamPINVOKE.new_i2psam_stream_settings(), true) {
  }

}
