//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class i2psamPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="SWIGRegisterExceptionCallbacks_i2psam")]
    public static extern void SWIGRegisterExceptionCallbacks_i2psam(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_i2psam")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_i2psam(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_i2psam(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_i2psam(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(i2psamPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(i2psamPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="SWIGRegisterStringCallback_i2psam")]
    public static extern void SWIGRegisterStringCallback_i2psam(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_i2psam(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static i2psamPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_DEFAULT_ADDRESS_get")]
  public static extern string SAM_DEFAULT_ADDRESS_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_DEFAULT_PORT_get")]
  public static extern int SAM_DEFAULT_PORT_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_GENERATE_MY_DESTINATION_get")]
  public static extern string SAM_GENERATE_MY_DESTINATION_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_MY_NAME_get")]
  public static extern string SAM_MY_NAME_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_DEFAULT_I2P_OPTIONS_get")]
  public static extern string SAM_DEFAULT_I2P_OPTIONS_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_SIGNATURE_TYPE_get")]
  public static extern string SAM_SIGNATURE_TYPE_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_NAME_INBOUND_QUANTITY_get")]
  public static extern string SAM_NAME_INBOUND_QUANTITY_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_DEFAULT_INBOUND_QUANTITY_get")]
  public static extern int SAM_DEFAULT_INBOUND_QUANTITY_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_NAME_INBOUND_LENGTH_get")]
  public static extern string SAM_NAME_INBOUND_LENGTH_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_DEFAULT_INBOUND_LENGTH_get")]
  public static extern int SAM_DEFAULT_INBOUND_LENGTH_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_NAME_INBOUND_LENGTHVARIANCE_get")]
  public static extern string SAM_NAME_INBOUND_LENGTHVARIANCE_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_DEFAULT_INBOUND_LENGTHVARIANCE_get")]
  public static extern int SAM_DEFAULT_INBOUND_LENGTHVARIANCE_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_NAME_INBOUND_BACKUPQUANTITY_get")]
  public static extern string SAM_NAME_INBOUND_BACKUPQUANTITY_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_DEFAULT_INBOUND_BACKUPQUANTITY_get")]
  public static extern int SAM_DEFAULT_INBOUND_BACKUPQUANTITY_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_NAME_INBOUND_ALLOWZEROHOP_get")]
  public static extern string SAM_NAME_INBOUND_ALLOWZEROHOP_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_NAME_INBOUND_IPRESTRICTION_get")]
  public static extern string SAM_NAME_INBOUND_IPRESTRICTION_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_DEFAULT_INBOUND_IPRESTRICTION_get")]
  public static extern int SAM_DEFAULT_INBOUND_IPRESTRICTION_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_NAME_OUTBOUND_QUANTITY_get")]
  public static extern string SAM_NAME_OUTBOUND_QUANTITY_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_DEFAULT_OUTBOUND_QUANTITY_get")]
  public static extern int SAM_DEFAULT_OUTBOUND_QUANTITY_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_NAME_OUTBOUND_LENGTH_get")]
  public static extern string SAM_NAME_OUTBOUND_LENGTH_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_DEFAULT_OUTBOUND_LENGTH_get")]
  public static extern int SAM_DEFAULT_OUTBOUND_LENGTH_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_NAME_OUTBOUND_LENGTHVARIANCE_get")]
  public static extern string SAM_NAME_OUTBOUND_LENGTHVARIANCE_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_DEFAULT_OUTBOUND_LENGTHVARIANCE_get")]
  public static extern int SAM_DEFAULT_OUTBOUND_LENGTHVARIANCE_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_NAME_OUTBOUND_BACKUPQUANTITY_get")]
  public static extern string SAM_NAME_OUTBOUND_BACKUPQUANTITY_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_DEFAULT_OUTBOUND_BACKUPQUANTITY_get")]
  public static extern int SAM_DEFAULT_OUTBOUND_BACKUPQUANTITY_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_NAME_OUTBOUND_ALLOWZEROHOP_get")]
  public static extern string SAM_NAME_OUTBOUND_ALLOWZEROHOP_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_NAME_OUTBOUND_IPRESTRICTION_get")]
  public static extern string SAM_NAME_OUTBOUND_IPRESTRICTION_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_DEFAULT_OUTBOUND_IPRESTRICTION_get")]
  public static extern int SAM_DEFAULT_OUTBOUND_IPRESTRICTION_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SAM_NAME_OUTBOUND_PRIORITY_get")]
  public static extern string SAM_NAME_OUTBOUND_PRIORITY_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_SOCKET_ERROR_get")]
  public static extern int SOCKET_ERROR_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_MAX_PATH_get")]
  public static extern int MAX_PATH_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_MSG_NOSIGNAL_get")]
  public static extern int MSG_NOSIGNAL_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_PRIO_MAX_get")]
  public static extern int PRIO_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_THREAD_PRIORITY_LOWEST_get")]
  public static extern int THREAD_PRIORITY_LOWEST_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_THREAD_PRIORITY_BELOW_NORMAL_get")]
  public static extern int THREAD_PRIORITY_BELOW_NORMAL_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_THREAD_PRIORITY_NORMAL_get")]
  public static extern int THREAD_PRIORITY_NORMAL_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_THREAD_PRIORITY_ABOVE_NORMAL_get")]
  public static extern int THREAD_PRIORITY_ABOVE_NORMAL_get();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_strnlen_int")]
  public static extern uint strnlen_int(string jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_stream_settings_samhost_set")]
  public static extern void i2psam_stream_settings_samhost_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_stream_settings_samhost_get")]
  public static extern string i2psam_stream_settings_samhost_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_stream_settings_samport_get")]
  public static extern global::System.IntPtr i2psam_stream_settings_samport_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_stream_settings_nickname_set")]
  public static extern void i2psam_stream_settings_nickname_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_stream_settings_nickname_get")]
  public static extern string i2psam_stream_settings_nickname_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_stream_settings_i2cp_opts_set")]
  public static extern void i2psam_stream_settings_i2cp_opts_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_stream_settings_i2cp_opts_get")]
  public static extern string i2psam_stream_settings_i2cp_opts_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_stream_settings_destination_set")]
  public static extern void i2psam_stream_settings_destination_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_stream_settings_destination_get")]
  public static extern string i2psam_stream_settings_destination_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_new_i2psam_stream_settings")]
  public static extern global::System.IntPtr new_i2psam_stream_settings();

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_delete_i2psam_stream_settings")]
  public static extern void delete_i2psam_stream_settings(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_stream_session_new")]
  public static extern global::System.IntPtr i2psam_stream_session_new(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_stream_session_free")]
  public static extern void i2psam_stream_session_free(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_get_samhost")]
  public static extern string i2psam_get_samhost(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_get_samport")]
  public static extern global::System.IntPtr i2psam_get_samport(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_get_nickname")]
  public static extern string i2psam_get_nickname(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_get_session_id")]
  public static extern string i2psam_get_session_id(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_get_sam_min_version")]
  public static extern string i2psam_get_sam_min_version(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_get_sam_max_version")]
  public static extern string i2psam_get_sam_max_version(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_get_sam_version")]
  public static extern string i2psam_get_sam_version(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_get_i2cp_options")]
  public static extern string i2psam_get_i2cp_options(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_is_sick")]
  public static extern int i2psam_is_sick(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_accept")]
  public static extern global::System.IntPtr i2psam_accept(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_connect")]
  public static extern global::System.IntPtr i2psam_connect(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_forward")]
  public static extern int i2psam_forward(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_namelookup")]
  public static extern string i2psam_namelookup(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_dest_generate")]
  public static extern global::System.IntPtr i2psam_dest_generate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_stop_forwarding")]
  public static extern void i2psam_stop_forwarding(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_stop_forwarding_all")]
  public static extern void i2psam_stop_forwarding_all(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_get_my_destination")]
  public static extern global::System.IntPtr i2psam_get_my_destination(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_write")]
  public static extern void i2psam_write(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_read")]
  public static extern string i2psam_read(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_socket_close")]
  public static extern void i2psam_socket_close(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_socket_is_ok")]
  public static extern int i2psam_socket_is_ok(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_socket_free")]
  public static extern void i2psam_socket_free(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_destination_priv")]
  public static extern string i2psam_destination_priv(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_destination_pub")]
  public static extern string i2psam_destination_pub(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("i2psam", EntryPoint="CSharp_i2psam_destination_free")]
  public static extern void i2psam_destination_free(global::System.Runtime.InteropServices.HandleRef jarg1);
}
