/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class i2psam_stream_settings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected i2psam_stream_settings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(i2psam_stream_settings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        i2psamJNI.delete_i2psam_stream_settings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSamhost(String value) {
    i2psamJNI.i2psam_stream_settings_samhost_set(swigCPtr, this, value);
  }

  public String getSamhost() {
    return i2psamJNI.i2psam_stream_settings_samhost_get(swigCPtr, this);
  }

  public SWIGTYPE_p_uint16_t getSamport() {
    return new SWIGTYPE_p_uint16_t(i2psamJNI.i2psam_stream_settings_samport_get(swigCPtr, this), true);
  }

  public void setNickname(String value) {
    i2psamJNI.i2psam_stream_settings_nickname_set(swigCPtr, this, value);
  }

  public String getNickname() {
    return i2psamJNI.i2psam_stream_settings_nickname_get(swigCPtr, this);
  }

  public void setI2cp_opts(String value) {
    i2psamJNI.i2psam_stream_settings_i2cp_opts_set(swigCPtr, this, value);
  }

  public String getI2cp_opts() {
    return i2psamJNI.i2psam_stream_settings_i2cp_opts_get(swigCPtr, this);
  }

  public void setDestination(String value) {
    i2psamJNI.i2psam_stream_settings_destination_set(swigCPtr, this, value);
  }

  public String getDestination() {
    return i2psamJNI.i2psam_stream_settings_destination_get(swigCPtr, this);
  }

  public i2psam_stream_settings() {
    this(i2psamJNI.new_i2psam_stream_settings(), true);
  }

}
