/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class i2psam implements i2psamConstants {
  public static long strnlen_int(String start, long max_len) {
    return i2psamJNI.strnlen_int(start, max_len);
  }

  public static SWIGTYPE_p_i2psam_stream_session i2psam_stream_session_new(i2psam_stream_settings arg0) {
    long cPtr = i2psamJNI.i2psam_stream_session_new(i2psam_stream_settings.getCPtr(arg0), arg0);
    return (cPtr == 0) ? null : new SWIGTYPE_p_i2psam_stream_session(cPtr, false);
  }

  public static void i2psam_stream_session_free(SWIGTYPE_p_i2psam_stream_session arg0) {
    i2psamJNI.i2psam_stream_session_free(SWIGTYPE_p_i2psam_stream_session.getCPtr(arg0));
  }

  public static String i2psam_get_samhost(SWIGTYPE_p_i2psam_stream_session arg0) {
    return i2psamJNI.i2psam_get_samhost(SWIGTYPE_p_i2psam_stream_session.getCPtr(arg0));
  }

  public static SWIGTYPE_p_uint16_t i2psam_get_samport(SWIGTYPE_p_i2psam_stream_session arg0) {
    return new SWIGTYPE_p_uint16_t(i2psamJNI.i2psam_get_samport(SWIGTYPE_p_i2psam_stream_session.getCPtr(arg0)), true);
  }

  public static String i2psam_get_nickname(SWIGTYPE_p_i2psam_stream_session arg0) {
    return i2psamJNI.i2psam_get_nickname(SWIGTYPE_p_i2psam_stream_session.getCPtr(arg0));
  }

  public static String i2psam_get_session_id(SWIGTYPE_p_i2psam_stream_session arg0) {
    return i2psamJNI.i2psam_get_session_id(SWIGTYPE_p_i2psam_stream_session.getCPtr(arg0));
  }

  public static String i2psam_get_sam_min_version(SWIGTYPE_p_i2psam_stream_session arg0) {
    return i2psamJNI.i2psam_get_sam_min_version(SWIGTYPE_p_i2psam_stream_session.getCPtr(arg0));
  }

  public static String i2psam_get_sam_max_version(SWIGTYPE_p_i2psam_stream_session arg0) {
    return i2psamJNI.i2psam_get_sam_max_version(SWIGTYPE_p_i2psam_stream_session.getCPtr(arg0));
  }

  public static String i2psam_get_sam_version(SWIGTYPE_p_i2psam_stream_session arg0) {
    return i2psamJNI.i2psam_get_sam_version(SWIGTYPE_p_i2psam_stream_session.getCPtr(arg0));
  }

  public static String i2psam_get_i2cp_options(SWIGTYPE_p_i2psam_stream_session arg0) {
    return i2psamJNI.i2psam_get_i2cp_options(SWIGTYPE_p_i2psam_stream_session.getCPtr(arg0));
  }

  public static int i2psam_is_sick(SWIGTYPE_p_i2psam_stream_session arg0) {
    return i2psamJNI.i2psam_is_sick(SWIGTYPE_p_i2psam_stream_session.getCPtr(arg0));
  }

  public static SWIGTYPE_p_i2psam_socket i2psam_accept(SWIGTYPE_p_i2psam_stream_session arg0, int silent) {
    long cPtr = i2psamJNI.i2psam_accept(SWIGTYPE_p_i2psam_stream_session.getCPtr(arg0), silent);
    return (cPtr == 0) ? null : new SWIGTYPE_p_i2psam_socket(cPtr, false);
  }

  public static SWIGTYPE_p_i2psam_socket i2psam_connect(SWIGTYPE_p_i2psam_stream_session arg0, String destination, int silent) {
    long cPtr = i2psamJNI.i2psam_connect(SWIGTYPE_p_i2psam_stream_session.getCPtr(arg0), destination, silent);
    return (cPtr == 0) ? null : new SWIGTYPE_p_i2psam_socket(cPtr, false);
  }

  public static int i2psam_forward(SWIGTYPE_p_i2psam_stream_session arg0, String host, SWIGTYPE_p_uint16_t port, int silent) {
    return i2psamJNI.i2psam_forward(SWIGTYPE_p_i2psam_stream_session.getCPtr(arg0), host, SWIGTYPE_p_uint16_t.getCPtr(port), silent);
  }

  public static String i2psam_namelookup(SWIGTYPE_p_i2psam_stream_session arg0, String name) {
    return i2psamJNI.i2psam_namelookup(SWIGTYPE_p_i2psam_stream_session.getCPtr(arg0), name);
  }

  public static SWIGTYPE_p_i2psam_destination i2psam_dest_generate(SWIGTYPE_p_i2psam_stream_session arg0) {
    long cPtr = i2psamJNI.i2psam_dest_generate(SWIGTYPE_p_i2psam_stream_session.getCPtr(arg0));
    return (cPtr == 0) ? null : new SWIGTYPE_p_i2psam_destination(cPtr, false);
  }

  public static void i2psam_stop_forwarding(SWIGTYPE_p_i2psam_stream_session arg0, String host, SWIGTYPE_p_uint16_t port) {
    i2psamJNI.i2psam_stop_forwarding(SWIGTYPE_p_i2psam_stream_session.getCPtr(arg0), host, SWIGTYPE_p_uint16_t.getCPtr(port));
  }

  public static void i2psam_stop_forwarding_all(SWIGTYPE_p_i2psam_stream_session arg0) {
    i2psamJNI.i2psam_stop_forwarding_all(SWIGTYPE_p_i2psam_stream_session.getCPtr(arg0));
  }

  public static SWIGTYPE_p_i2psam_destination i2psam_get_my_destination(SWIGTYPE_p_i2psam_stream_session arg0) {
    long cPtr = i2psamJNI.i2psam_get_my_destination(SWIGTYPE_p_i2psam_stream_session.getCPtr(arg0));
    return (cPtr == 0) ? null : new SWIGTYPE_p_i2psam_destination(cPtr, false);
  }

  public static void i2psam_write(SWIGTYPE_p_i2psam_socket arg0, String data, long dlen) {
    i2psamJNI.i2psam_write(SWIGTYPE_p_i2psam_socket.getCPtr(arg0), data, dlen);
  }

  public static String i2psam_read(SWIGTYPE_p_i2psam_socket arg0, SWIGTYPE_p_size_t dlen) {
    return i2psamJNI.i2psam_read(SWIGTYPE_p_i2psam_socket.getCPtr(arg0), SWIGTYPE_p_size_t.getCPtr(dlen));
  }

  public static void i2psam_socket_close(SWIGTYPE_p_i2psam_socket arg0) {
    i2psamJNI.i2psam_socket_close(SWIGTYPE_p_i2psam_socket.getCPtr(arg0));
  }

  public static int i2psam_socket_is_ok(SWIGTYPE_p_i2psam_socket arg0) {
    return i2psamJNI.i2psam_socket_is_ok(SWIGTYPE_p_i2psam_socket.getCPtr(arg0));
  }

  public static void i2psam_socket_free(SWIGTYPE_p_i2psam_socket arg0) {
    i2psamJNI.i2psam_socket_free(SWIGTYPE_p_i2psam_socket.getCPtr(arg0));
  }

  public static String i2psam_destination_priv(SWIGTYPE_p_i2psam_destination arg0) {
    return i2psamJNI.i2psam_destination_priv(SWIGTYPE_p_i2psam_destination.getCPtr(arg0));
  }

  public static String i2psam_destination_pub(SWIGTYPE_p_i2psam_destination arg0) {
    return i2psamJNI.i2psam_destination_pub(SWIGTYPE_p_i2psam_destination.getCPtr(arg0));
  }

  public static void i2psam_destination_free(SWIGTYPE_p_i2psam_destination arg0) {
    i2psamJNI.i2psam_destination_free(SWIGTYPE_p_i2psam_destination.getCPtr(arg0));
  }

}
