/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface i2psamConstants {
  public final static String SAM_DEFAULT_ADDRESS = i2psamJNI.SAM_DEFAULT_ADDRESS_get();
  public final static int SAM_DEFAULT_PORT = i2psamJNI.SAM_DEFAULT_PORT_get();
  public final static String SAM_GENERATE_MY_DESTINATION = i2psamJNI.SAM_GENERATE_MY_DESTINATION_get();
  public final static String SAM_MY_NAME = i2psamJNI.SAM_MY_NAME_get();
  public final static String SAM_DEFAULT_I2P_OPTIONS = i2psamJNI.SAM_DEFAULT_I2P_OPTIONS_get();
  public final static String SAM_SIGNATURE_TYPE = i2psamJNI.SAM_SIGNATURE_TYPE_get();
  public final static String SAM_NAME_INBOUND_QUANTITY = i2psamJNI.SAM_NAME_INBOUND_QUANTITY_get();
  public final static int SAM_DEFAULT_INBOUND_QUANTITY = i2psamJNI.SAM_DEFAULT_INBOUND_QUANTITY_get();
  public final static String SAM_NAME_INBOUND_LENGTH = i2psamJNI.SAM_NAME_INBOUND_LENGTH_get();
  public final static int SAM_DEFAULT_INBOUND_LENGTH = i2psamJNI.SAM_DEFAULT_INBOUND_LENGTH_get();
  public final static String SAM_NAME_INBOUND_LENGTHVARIANCE = i2psamJNI.SAM_NAME_INBOUND_LENGTHVARIANCE_get();
  public final static int SAM_DEFAULT_INBOUND_LENGTHVARIANCE = i2psamJNI.SAM_DEFAULT_INBOUND_LENGTHVARIANCE_get();
  public final static String SAM_NAME_INBOUND_BACKUPQUANTITY = i2psamJNI.SAM_NAME_INBOUND_BACKUPQUANTITY_get();
  public final static int SAM_DEFAULT_INBOUND_BACKUPQUANTITY = i2psamJNI.SAM_DEFAULT_INBOUND_BACKUPQUANTITY_get();
  public final static String SAM_NAME_INBOUND_ALLOWZEROHOP = i2psamJNI.SAM_NAME_INBOUND_ALLOWZEROHOP_get();
  public final static String SAM_NAME_INBOUND_IPRESTRICTION = i2psamJNI.SAM_NAME_INBOUND_IPRESTRICTION_get();
  public final static int SAM_DEFAULT_INBOUND_IPRESTRICTION = i2psamJNI.SAM_DEFAULT_INBOUND_IPRESTRICTION_get();
  public final static String SAM_NAME_OUTBOUND_QUANTITY = i2psamJNI.SAM_NAME_OUTBOUND_QUANTITY_get();
  public final static int SAM_DEFAULT_OUTBOUND_QUANTITY = i2psamJNI.SAM_DEFAULT_OUTBOUND_QUANTITY_get();
  public final static String SAM_NAME_OUTBOUND_LENGTH = i2psamJNI.SAM_NAME_OUTBOUND_LENGTH_get();
  public final static int SAM_DEFAULT_OUTBOUND_LENGTH = i2psamJNI.SAM_DEFAULT_OUTBOUND_LENGTH_get();
  public final static String SAM_NAME_OUTBOUND_LENGTHVARIANCE = i2psamJNI.SAM_NAME_OUTBOUND_LENGTHVARIANCE_get();
  public final static int SAM_DEFAULT_OUTBOUND_LENGTHVARIANCE = i2psamJNI.SAM_DEFAULT_OUTBOUND_LENGTHVARIANCE_get();
  public final static String SAM_NAME_OUTBOUND_BACKUPQUANTITY = i2psamJNI.SAM_NAME_OUTBOUND_BACKUPQUANTITY_get();
  public final static int SAM_DEFAULT_OUTBOUND_BACKUPQUANTITY = i2psamJNI.SAM_DEFAULT_OUTBOUND_BACKUPQUANTITY_get();
  public final static String SAM_NAME_OUTBOUND_ALLOWZEROHOP = i2psamJNI.SAM_NAME_OUTBOUND_ALLOWZEROHOP_get();
  public final static String SAM_NAME_OUTBOUND_IPRESTRICTION = i2psamJNI.SAM_NAME_OUTBOUND_IPRESTRICTION_get();
  public final static int SAM_DEFAULT_OUTBOUND_IPRESTRICTION = i2psamJNI.SAM_DEFAULT_OUTBOUND_IPRESTRICTION_get();
  public final static String SAM_NAME_OUTBOUND_PRIORITY = i2psamJNI.SAM_NAME_OUTBOUND_PRIORITY_get();
  public final static int SOCKET_ERROR = i2psamJNI.SOCKET_ERROR_get();
  public final static int MAX_PATH = i2psamJNI.MAX_PATH_get();
  public final static int MSG_NOSIGNAL = i2psamJNI.MSG_NOSIGNAL_get();
  public final static int PRIO_MAX = i2psamJNI.PRIO_MAX_get();
  public final static int THREAD_PRIORITY_LOWEST = i2psamJNI.THREAD_PRIORITY_LOWEST_get();
  public final static int THREAD_PRIORITY_BELOW_NORMAL = i2psamJNI.THREAD_PRIORITY_BELOW_NORMAL_get();
  public final static int THREAD_PRIORITY_NORMAL = i2psamJNI.THREAD_PRIORITY_NORMAL_get();
  public final static int THREAD_PRIORITY_ABOVE_NORMAL = i2psamJNI.THREAD_PRIORITY_ABOVE_NORMAL_get();
}
