/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class i2psamJNI {
  public final static native String SAM_DEFAULT_ADDRESS_get();
  public final static native int SAM_DEFAULT_PORT_get();
  public final static native String SAM_GENERATE_MY_DESTINATION_get();
  public final static native String SAM_MY_NAME_get();
  public final static native String SAM_DEFAULT_I2P_OPTIONS_get();
  public final static native String SAM_SIGNATURE_TYPE_get();
  public final static native String SAM_NAME_INBOUND_QUANTITY_get();
  public final static native int SAM_DEFAULT_INBOUND_QUANTITY_get();
  public final static native String SAM_NAME_INBOUND_LENGTH_get();
  public final static native int SAM_DEFAULT_INBOUND_LENGTH_get();
  public final static native String SAM_NAME_INBOUND_LENGTHVARIANCE_get();
  public final static native int SAM_DEFAULT_INBOUND_LENGTHVARIANCE_get();
  public final static native String SAM_NAME_INBOUND_BACKUPQUANTITY_get();
  public final static native int SAM_DEFAULT_INBOUND_BACKUPQUANTITY_get();
  public final static native String SAM_NAME_INBOUND_ALLOWZEROHOP_get();
  public final static native String SAM_NAME_INBOUND_IPRESTRICTION_get();
  public final static native int SAM_DEFAULT_INBOUND_IPRESTRICTION_get();
  public final static native String SAM_NAME_OUTBOUND_QUANTITY_get();
  public final static native int SAM_DEFAULT_OUTBOUND_QUANTITY_get();
  public final static native String SAM_NAME_OUTBOUND_LENGTH_get();
  public final static native int SAM_DEFAULT_OUTBOUND_LENGTH_get();
  public final static native String SAM_NAME_OUTBOUND_LENGTHVARIANCE_get();
  public final static native int SAM_DEFAULT_OUTBOUND_LENGTHVARIANCE_get();
  public final static native String SAM_NAME_OUTBOUND_BACKUPQUANTITY_get();
  public final static native int SAM_DEFAULT_OUTBOUND_BACKUPQUANTITY_get();
  public final static native String SAM_NAME_OUTBOUND_ALLOWZEROHOP_get();
  public final static native String SAM_NAME_OUTBOUND_IPRESTRICTION_get();
  public final static native int SAM_DEFAULT_OUTBOUND_IPRESTRICTION_get();
  public final static native String SAM_NAME_OUTBOUND_PRIORITY_get();
  public final static native int SOCKET_ERROR_get();
  public final static native int MAX_PATH_get();
  public final static native int MSG_NOSIGNAL_get();
  public final static native int PRIO_MAX_get();
  public final static native int THREAD_PRIORITY_LOWEST_get();
  public final static native int THREAD_PRIORITY_BELOW_NORMAL_get();
  public final static native int THREAD_PRIORITY_NORMAL_get();
  public final static native int THREAD_PRIORITY_ABOVE_NORMAL_get();
  public final static native long strnlen_int(String jarg1, long jarg2);
  public final static native void i2psam_stream_settings_samhost_set(long jarg1, i2psam_stream_settings jarg1_, String jarg2);
  public final static native String i2psam_stream_settings_samhost_get(long jarg1, i2psam_stream_settings jarg1_);
  public final static native long i2psam_stream_settings_samport_get(long jarg1, i2psam_stream_settings jarg1_);
  public final static native void i2psam_stream_settings_nickname_set(long jarg1, i2psam_stream_settings jarg1_, String jarg2);
  public final static native String i2psam_stream_settings_nickname_get(long jarg1, i2psam_stream_settings jarg1_);
  public final static native void i2psam_stream_settings_i2cp_opts_set(long jarg1, i2psam_stream_settings jarg1_, String jarg2);
  public final static native String i2psam_stream_settings_i2cp_opts_get(long jarg1, i2psam_stream_settings jarg1_);
  public final static native void i2psam_stream_settings_destination_set(long jarg1, i2psam_stream_settings jarg1_, String jarg2);
  public final static native String i2psam_stream_settings_destination_get(long jarg1, i2psam_stream_settings jarg1_);
  public final static native long new_i2psam_stream_settings();
  public final static native void delete_i2psam_stream_settings(long jarg1);
  public final static native long i2psam_stream_session_new(long jarg1, i2psam_stream_settings jarg1_);
  public final static native void i2psam_stream_session_free(long jarg1);
  public final static native String i2psam_get_samhost(long jarg1);
  public final static native long i2psam_get_samport(long jarg1);
  public final static native String i2psam_get_nickname(long jarg1);
  public final static native String i2psam_get_session_id(long jarg1);
  public final static native String i2psam_get_sam_min_version(long jarg1);
  public final static native String i2psam_get_sam_max_version(long jarg1);
  public final static native String i2psam_get_sam_version(long jarg1);
  public final static native String i2psam_get_i2cp_options(long jarg1);
  public final static native int i2psam_is_sick(long jarg1);
  public final static native long i2psam_accept(long jarg1, int jarg2);
  public final static native long i2psam_connect(long jarg1, String jarg2, int jarg3);
  public final static native int i2psam_forward(long jarg1, String jarg2, long jarg3, int jarg4);
  public final static native String i2psam_namelookup(long jarg1, String jarg2);
  public final static native long i2psam_dest_generate(long jarg1);
  public final static native void i2psam_stop_forwarding(long jarg1, String jarg2, long jarg3);
  public final static native void i2psam_stop_forwarding_all(long jarg1);
  public final static native long i2psam_get_my_destination(long jarg1);
  public final static native void i2psam_write(long jarg1, String jarg2, long jarg3);
  public final static native String i2psam_read(long jarg1, long jarg2);
  public final static native void i2psam_socket_close(long jarg1);
  public final static native int i2psam_socket_is_ok(long jarg1);
  public final static native void i2psam_socket_free(long jarg1);
  public final static native String i2psam_destination_priv(long jarg1);
  public final static native String i2psam_destination_pub(long jarg1);
  public final static native void i2psam_destination_free(long jarg1);
}
