/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: i2psam.swigcxx

package i2psam

import "unsafe"
import _ "runtime/cgo"
import "sync"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

var _wrap_Swig_free_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_Swig_free(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Swig_free_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func Swig_free(arg1 uintptr) {
	_swig_wrap_Swig_free(arg1)
}

var _wrap_Swig_malloc_i2psam_14c5794ad19f3432 unsafe.Pointer

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_Swig_malloc_i2psam_14c5794ad19f3432, _swig_p)
	return
}
const SAM_DEFAULT_ADDRESS string = "127.0.0.1"
const SAM_DEFAULT_PORT int = 7656
const SAM_GENERATE_MY_DESTINATION string = "TRANSIENT"
const SAM_MY_NAME string = "ME"
var _wrap_SAM_DEFAULT_I2P_OPTIONS_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_SAM_DEFAULT_I2P_OPTIONS() (base string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_SAM_DEFAULT_I2P_OPTIONS_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func _swig_getSAM_DEFAULT_I2P_OPTIONS() (_swig_ret string) {
	var swig_r string
	swig_r = _swig_wrap_SAM_DEFAULT_I2P_OPTIONS()
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var SAM_DEFAULT_I2P_OPTIONS string = _swig_getSAM_DEFAULT_I2P_OPTIONS()
const SAM_SIGNATURE_TYPE string = "ECDSA_SHA256_P256"
const SAM_NAME_INBOUND_QUANTITY string = "inbound.quantity"
const SAM_DEFAULT_INBOUND_QUANTITY int = 3
const SAM_NAME_INBOUND_LENGTH string = "inbound.length"
const SAM_DEFAULT_INBOUND_LENGTH int = 3
const SAM_NAME_INBOUND_LENGTHVARIANCE string = "inbound.lengthVariance"
const SAM_DEFAULT_INBOUND_LENGTHVARIANCE int = 0
const SAM_NAME_INBOUND_BACKUPQUANTITY string = "inbound.backupQuantity"
const SAM_DEFAULT_INBOUND_BACKUPQUANTITY int = 1
const SAM_NAME_INBOUND_ALLOWZEROHOP string = "inbound.allowZeroHop"
const SAM_NAME_INBOUND_IPRESTRICTION string = "inbound.IPRestriction"
const SAM_DEFAULT_INBOUND_IPRESTRICTION int = 2
const SAM_NAME_OUTBOUND_QUANTITY string = "outbound.quantity"
const SAM_DEFAULT_OUTBOUND_QUANTITY int = 3
const SAM_NAME_OUTBOUND_LENGTH string = "outbound.length"
const SAM_DEFAULT_OUTBOUND_LENGTH int = 3
const SAM_NAME_OUTBOUND_LENGTHVARIANCE string = "outbound.lengthVariance"
const SAM_DEFAULT_OUTBOUND_LENGTHVARIANCE int = 0
const SAM_NAME_OUTBOUND_BACKUPQUANTITY string = "outbound.backupQuantity"
const SAM_DEFAULT_OUTBOUND_BACKUPQUANTITY int = 1
const SAM_NAME_OUTBOUND_ALLOWZEROHOP string = "outbound.allowZeroHop"
const SAM_NAME_OUTBOUND_IPRESTRICTION string = "outbound.IPRestriction"
const SAM_DEFAULT_OUTBOUND_IPRESTRICTION int = 2
const SAM_NAME_OUTBOUND_PRIORITY string = "outbound.priority"
const SOCKET_ERROR int = -1
const MAX_PATH int = 1024
const MSG_NOSIGNAL int = 0
const PRIO_MAX int = 20
const THREAD_PRIORITY_LOWEST int = 20
const THREAD_PRIORITY_BELOW_NORMAL int = 2
const THREAD_PRIORITY_NORMAL int = 0
var _wrap_THREAD_PRIORITY_ABOVE_NORMAL_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_getTHREAD_PRIORITY_ABOVE_NORMAL() (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_THREAD_PRIORITY_ABOVE_NORMAL_i2psam_14c5794ad19f3432, _swig_p)
	return
}
var THREAD_PRIORITY_ABOVE_NORMAL int = _swig_getTHREAD_PRIORITY_ABOVE_NORMAL()
var _wrap_strnlen_int_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_strnlen_int(base string, _ int64) (_ int64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_strnlen_int_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func Strnlen_int(arg1 string, arg2 int64) (_swig_ret int64) {
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return _swig_wrap_strnlen_int(arg1, arg2)
}

type SwigcptrI2psam_stream_settings uintptr

func (p SwigcptrI2psam_stream_settings) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrI2psam_stream_settings) SwigIsI2psam_stream_settings() {
}

var _wrap_i2psam_stream_settings_samhost_set_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_stream_settings_samhost_set(base SwigcptrI2psam_stream_settings, _ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_stream_settings_samhost_set_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func (arg1 SwigcptrI2psam_stream_settings) SetSamhost(arg2 string) {
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	_swig_wrap_i2psam_stream_settings_samhost_set(arg1, arg2)
}

var _wrap_i2psam_stream_settings_samhost_get_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_stream_settings_samhost_get(base SwigcptrI2psam_stream_settings) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_stream_settings_samhost_get_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func (arg1 SwigcptrI2psam_stream_settings) GetSamhost() (_swig_ret string) {
	var swig_r string
	swig_r = _swig_wrap_i2psam_stream_settings_samhost_get(arg1)
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var _wrap_i2psam_stream_settings_samport_get_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_stream_settings_samport_get(base SwigcptrI2psam_stream_settings) (_ SwigcptrUint16_t) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_stream_settings_samport_get_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func (arg1 SwigcptrI2psam_stream_settings) GetSamport() (_swig_ret Uint16_t) {
	return _swig_wrap_i2psam_stream_settings_samport_get(arg1)
}

var _wrap_i2psam_stream_settings_nickname_set_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_stream_settings_nickname_set(base SwigcptrI2psam_stream_settings, _ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_stream_settings_nickname_set_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func (arg1 SwigcptrI2psam_stream_settings) SetNickname(arg2 string) {
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	_swig_wrap_i2psam_stream_settings_nickname_set(arg1, arg2)
}

var _wrap_i2psam_stream_settings_nickname_get_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_stream_settings_nickname_get(base SwigcptrI2psam_stream_settings) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_stream_settings_nickname_get_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func (arg1 SwigcptrI2psam_stream_settings) GetNickname() (_swig_ret string) {
	var swig_r string
	swig_r = _swig_wrap_i2psam_stream_settings_nickname_get(arg1)
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var _wrap_i2psam_stream_settings_i2cp_opts_set_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_stream_settings_i2cp_opts_set(base SwigcptrI2psam_stream_settings, _ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_stream_settings_i2cp_opts_set_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func (arg1 SwigcptrI2psam_stream_settings) SetI2cp_opts(arg2 string) {
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	_swig_wrap_i2psam_stream_settings_i2cp_opts_set(arg1, arg2)
}

var _wrap_i2psam_stream_settings_i2cp_opts_get_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_stream_settings_i2cp_opts_get(base SwigcptrI2psam_stream_settings) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_stream_settings_i2cp_opts_get_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func (arg1 SwigcptrI2psam_stream_settings) GetI2cp_opts() (_swig_ret string) {
	var swig_r string
	swig_r = _swig_wrap_i2psam_stream_settings_i2cp_opts_get(arg1)
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var _wrap_i2psam_stream_settings_destination_set_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_stream_settings_destination_set(base SwigcptrI2psam_stream_settings, _ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_stream_settings_destination_set_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func (arg1 SwigcptrI2psam_stream_settings) SetDestination(arg2 string) {
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	_swig_wrap_i2psam_stream_settings_destination_set(arg1, arg2)
}

var _wrap_i2psam_stream_settings_destination_get_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_stream_settings_destination_get(base SwigcptrI2psam_stream_settings) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_stream_settings_destination_get_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func (arg1 SwigcptrI2psam_stream_settings) GetDestination() (_swig_ret string) {
	var swig_r string
	swig_r = _swig_wrap_i2psam_stream_settings_destination_get(arg1)
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var _wrap_new_i2psam_stream_settings_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_new_i2psam_stream_settings() (base SwigcptrI2psam_stream_settings) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_i2psam_stream_settings_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func NewI2psam_stream_settings() (_swig_ret I2psam_stream_settings) {
	return _swig_wrap_new_i2psam_stream_settings()
}

var _wrap_delete_i2psam_stream_settings_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_delete_i2psam_stream_settings(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_i2psam_stream_settings_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func DeleteI2psam_stream_settings(arg1 I2psam_stream_settings) {
	_swig_wrap_delete_i2psam_stream_settings(arg1.Swigcptr())
}

type I2psam_stream_settings interface {
	Swigcptr() uintptr
	SwigIsI2psam_stream_settings()
	SetSamhost(arg2 string)
	GetSamhost() (_swig_ret string)
	GetSamport() (_swig_ret Uint16_t)
	SetNickname(arg2 string)
	GetNickname() (_swig_ret string)
	SetI2cp_opts(arg2 string)
	GetI2cp_opts() (_swig_ret string)
	SetDestination(arg2 string)
	GetDestination() (_swig_ret string)
}

var _wrap_i2psam_stream_session_new_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_stream_session_new(base uintptr) (_ SwigcptrStruct_SS_i2psam_stream_session) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_stream_session_new_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_stream_session_new(arg1 I2psam_stream_settings) (_swig_ret Struct_SS_i2psam_stream_session) {
	return _swig_wrap_i2psam_stream_session_new(arg1.Swigcptr())
}

var _wrap_i2psam_stream_session_free_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_stream_session_free(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_stream_session_free_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_stream_session_free(arg1 Struct_SS_i2psam_stream_session) {
	_swig_wrap_i2psam_stream_session_free(arg1.Swigcptr())
}

var _wrap_i2psam_get_samhost_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_get_samhost(base uintptr) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_get_samhost_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_get_samhost(arg1 Struct_SS_i2psam_stream_session) (_swig_ret string) {
	var swig_r string
	swig_r = _swig_wrap_i2psam_get_samhost(arg1.Swigcptr())
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var _wrap_i2psam_get_samport_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_get_samport(base uintptr) (_ SwigcptrUint16_t) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_get_samport_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_get_samport(arg1 Struct_SS_i2psam_stream_session) (_swig_ret Uint16_t) {
	return _swig_wrap_i2psam_get_samport(arg1.Swigcptr())
}

var _wrap_i2psam_get_nickname_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_get_nickname(base uintptr) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_get_nickname_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_get_nickname(arg1 Struct_SS_i2psam_stream_session) (_swig_ret string) {
	var swig_r string
	swig_r = _swig_wrap_i2psam_get_nickname(arg1.Swigcptr())
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var _wrap_i2psam_get_session_id_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_get_session_id(base uintptr) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_get_session_id_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_get_session_id(arg1 Struct_SS_i2psam_stream_session) (_swig_ret string) {
	var swig_r string
	swig_r = _swig_wrap_i2psam_get_session_id(arg1.Swigcptr())
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var _wrap_i2psam_get_sam_min_version_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_get_sam_min_version(base uintptr) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_get_sam_min_version_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_get_sam_min_version(arg1 Struct_SS_i2psam_stream_session) (_swig_ret string) {
	var swig_r string
	swig_r = _swig_wrap_i2psam_get_sam_min_version(arg1.Swigcptr())
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var _wrap_i2psam_get_sam_max_version_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_get_sam_max_version(base uintptr) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_get_sam_max_version_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_get_sam_max_version(arg1 Struct_SS_i2psam_stream_session) (_swig_ret string) {
	var swig_r string
	swig_r = _swig_wrap_i2psam_get_sam_max_version(arg1.Swigcptr())
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var _wrap_i2psam_get_sam_version_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_get_sam_version(base uintptr) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_get_sam_version_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_get_sam_version(arg1 Struct_SS_i2psam_stream_session) (_swig_ret string) {
	var swig_r string
	swig_r = _swig_wrap_i2psam_get_sam_version(arg1.Swigcptr())
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var _wrap_i2psam_get_i2cp_options_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_get_i2cp_options(base uintptr) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_get_i2cp_options_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_get_i2cp_options(arg1 Struct_SS_i2psam_stream_session) (_swig_ret string) {
	var swig_r string
	swig_r = _swig_wrap_i2psam_get_i2cp_options(arg1.Swigcptr())
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var _wrap_i2psam_is_sick_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_is_sick(base uintptr) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_is_sick_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_is_sick(arg1 Struct_SS_i2psam_stream_session) (_swig_ret int) {
	return _swig_wrap_i2psam_is_sick(arg1.Swigcptr())
}

var _wrap_i2psam_accept_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_accept(base uintptr, _ int) (_ SwigcptrStruct_SS_i2psam_socket) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_accept_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_accept(arg1 Struct_SS_i2psam_stream_session, arg2 int) (_swig_ret Struct_SS_i2psam_socket) {
	return _swig_wrap_i2psam_accept(arg1.Swigcptr(), arg2)
}

var _wrap_i2psam_connect_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_connect(base uintptr, _ string, _ int) (_ SwigcptrStruct_SS_i2psam_socket) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_connect_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_connect(arg1 Struct_SS_i2psam_stream_session, arg2 string, arg3 int) (_swig_ret Struct_SS_i2psam_socket) {
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return _swig_wrap_i2psam_connect(arg1.Swigcptr(), arg2, arg3)
}

var _wrap_i2psam_forward_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_forward(base uintptr, _ string, _ uintptr, _ int) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_forward_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_forward(arg1 Struct_SS_i2psam_stream_session, arg2 string, arg3 Uint16_t, arg4 int) (_swig_ret int) {
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return _swig_wrap_i2psam_forward(arg1.Swigcptr(), arg2, arg3.Swigcptr(), arg4)
}

var _wrap_i2psam_namelookup_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_namelookup(base uintptr, _ string) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_namelookup_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_namelookup(arg1 Struct_SS_i2psam_stream_session, arg2 string) (_swig_ret string) {
	var swig_r string
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	swig_r = _swig_wrap_i2psam_namelookup(arg1.Swigcptr(), arg2)
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var _wrap_i2psam_dest_generate_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_dest_generate(base uintptr) (_ SwigcptrStruct_SS_i2psam_destination) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_dest_generate_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_dest_generate(arg1 Struct_SS_i2psam_stream_session) (_swig_ret Struct_SS_i2psam_destination) {
	return _swig_wrap_i2psam_dest_generate(arg1.Swigcptr())
}

var _wrap_i2psam_stop_forwarding_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_stop_forwarding(base uintptr, _ string, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_stop_forwarding_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_stop_forwarding(arg1 Struct_SS_i2psam_stream_session, arg2 string, arg3 Uint16_t) {
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	_swig_wrap_i2psam_stop_forwarding(arg1.Swigcptr(), arg2, arg3.Swigcptr())
}

var _wrap_i2psam_stop_forwarding_all_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_stop_forwarding_all(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_stop_forwarding_all_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_stop_forwarding_all(arg1 Struct_SS_i2psam_stream_session) {
	_swig_wrap_i2psam_stop_forwarding_all(arg1.Swigcptr())
}

var _wrap_i2psam_get_my_destination_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_get_my_destination(base uintptr) (_ SwigcptrStruct_SS_i2psam_destination) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_get_my_destination_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_get_my_destination(arg1 Struct_SS_i2psam_stream_session) (_swig_ret Struct_SS_i2psam_destination) {
	return _swig_wrap_i2psam_get_my_destination(arg1.Swigcptr())
}

var _wrap_i2psam_write_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_write(base uintptr, _ string, _ int64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_write_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_write(arg1 Struct_SS_i2psam_socket, arg2 string, arg3 int64) {
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	_swig_wrap_i2psam_write(arg1.Swigcptr(), arg2, arg3)
}

var _wrap_i2psam_read_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_read(base uintptr, _ *int64) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_read_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_read(arg1 Struct_SS_i2psam_socket, arg2 *int64) (_swig_ret string) {
	var swig_r string
	swig_r = _swig_wrap_i2psam_read(arg1.Swigcptr(), arg2)
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var _wrap_i2psam_socket_close_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_socket_close(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_socket_close_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_socket_close(arg1 Struct_SS_i2psam_socket) {
	_swig_wrap_i2psam_socket_close(arg1.Swigcptr())
}

var _wrap_i2psam_socket_is_ok_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_socket_is_ok(base uintptr) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_socket_is_ok_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_socket_is_ok(arg1 Struct_SS_i2psam_socket) (_swig_ret int) {
	return _swig_wrap_i2psam_socket_is_ok(arg1.Swigcptr())
}

var _wrap_i2psam_socket_free_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_socket_free(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_socket_free_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_socket_free(arg1 Struct_SS_i2psam_socket) {
	_swig_wrap_i2psam_socket_free(arg1.Swigcptr())
}

var _wrap_i2psam_destination_priv_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_destination_priv(base uintptr) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_destination_priv_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_destination_priv(arg1 Struct_SS_i2psam_destination) (_swig_ret string) {
	var swig_r string
	swig_r = _swig_wrap_i2psam_destination_priv(arg1.Swigcptr())
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var _wrap_i2psam_destination_pub_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_destination_pub(base uintptr) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_destination_pub_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_destination_pub(arg1 Struct_SS_i2psam_destination) (_swig_ret string) {
	var swig_r string
	swig_r = _swig_wrap_i2psam_destination_pub(arg1.Swigcptr())
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var _wrap_i2psam_destination_free_i2psam_14c5794ad19f3432 unsafe.Pointer

func _swig_wrap_i2psam_destination_free(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_i2psam_destination_free_i2psam_14c5794ad19f3432, _swig_p)
	return
}

func I2psam_destination_free(arg1 Struct_SS_i2psam_destination) {
	_swig_wrap_i2psam_destination_free(arg1.Swigcptr())
}


type SwigcptrStruct_SS_i2psam_destination uintptr
type Struct_SS_i2psam_destination interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_i2psam_destination) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrUint16_t uintptr
type Uint16_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrUint16_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_i2psam_stream_session uintptr
type Struct_SS_i2psam_stream_session interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_i2psam_stream_session) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_i2psam_socket uintptr
type Struct_SS_i2psam_socket interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_i2psam_socket) Swigcptr() uintptr {
	return uintptr(p)
}

