/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module i2psam;

static import i2psam_im;
static import tango.stdc.config;
static import tango.stdc.stringz;


char[] SAM_DEFAULT_ADDRESS() {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.SAM_DEFAULT_ADDRESS_get());
  return ret;
}

int SAM_DEFAULT_PORT() {
  auto ret = i2psam_im.SAM_DEFAULT_PORT_get();
  return ret;
}

char[] SAM_GENERATE_MY_DESTINATION() {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.SAM_GENERATE_MY_DESTINATION_get());
  return ret;
}

char[] SAM_MY_NAME() {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.SAM_MY_NAME_get());
  return ret;
}

char[] SAM_DEFAULT_I2P_OPTIONS() {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.SAM_DEFAULT_I2P_OPTIONS_get());
  return ret;
}

char[] SAM_SIGNATURE_TYPE() {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.SAM_SIGNATURE_TYPE_get());
  return ret;
}

char[] SAM_NAME_INBOUND_QUANTITY() {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.SAM_NAME_INBOUND_QUANTITY_get());
  return ret;
}

int SAM_DEFAULT_INBOUND_QUANTITY() {
  auto ret = i2psam_im.SAM_DEFAULT_INBOUND_QUANTITY_get();
  return ret;
}

char[] SAM_NAME_INBOUND_LENGTH() {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.SAM_NAME_INBOUND_LENGTH_get());
  return ret;
}

int SAM_DEFAULT_INBOUND_LENGTH() {
  auto ret = i2psam_im.SAM_DEFAULT_INBOUND_LENGTH_get();
  return ret;
}

char[] SAM_NAME_INBOUND_LENGTHVARIANCE() {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.SAM_NAME_INBOUND_LENGTHVARIANCE_get());
  return ret;
}

int SAM_DEFAULT_INBOUND_LENGTHVARIANCE() {
  auto ret = i2psam_im.SAM_DEFAULT_INBOUND_LENGTHVARIANCE_get();
  return ret;
}

char[] SAM_NAME_INBOUND_BACKUPQUANTITY() {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.SAM_NAME_INBOUND_BACKUPQUANTITY_get());
  return ret;
}

int SAM_DEFAULT_INBOUND_BACKUPQUANTITY() {
  auto ret = i2psam_im.SAM_DEFAULT_INBOUND_BACKUPQUANTITY_get();
  return ret;
}

char[] SAM_NAME_INBOUND_ALLOWZEROHOP() {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.SAM_NAME_INBOUND_ALLOWZEROHOP_get());
  return ret;
}

char[] SAM_NAME_INBOUND_IPRESTRICTION() {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.SAM_NAME_INBOUND_IPRESTRICTION_get());
  return ret;
}

int SAM_DEFAULT_INBOUND_IPRESTRICTION() {
  auto ret = i2psam_im.SAM_DEFAULT_INBOUND_IPRESTRICTION_get();
  return ret;
}

char[] SAM_NAME_OUTBOUND_QUANTITY() {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.SAM_NAME_OUTBOUND_QUANTITY_get());
  return ret;
}

int SAM_DEFAULT_OUTBOUND_QUANTITY() {
  auto ret = i2psam_im.SAM_DEFAULT_OUTBOUND_QUANTITY_get();
  return ret;
}

char[] SAM_NAME_OUTBOUND_LENGTH() {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.SAM_NAME_OUTBOUND_LENGTH_get());
  return ret;
}

int SAM_DEFAULT_OUTBOUND_LENGTH() {
  auto ret = i2psam_im.SAM_DEFAULT_OUTBOUND_LENGTH_get();
  return ret;
}

char[] SAM_NAME_OUTBOUND_LENGTHVARIANCE() {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.SAM_NAME_OUTBOUND_LENGTHVARIANCE_get());
  return ret;
}

int SAM_DEFAULT_OUTBOUND_LENGTHVARIANCE() {
  auto ret = i2psam_im.SAM_DEFAULT_OUTBOUND_LENGTHVARIANCE_get();
  return ret;
}

char[] SAM_NAME_OUTBOUND_BACKUPQUANTITY() {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.SAM_NAME_OUTBOUND_BACKUPQUANTITY_get());
  return ret;
}

int SAM_DEFAULT_OUTBOUND_BACKUPQUANTITY() {
  auto ret = i2psam_im.SAM_DEFAULT_OUTBOUND_BACKUPQUANTITY_get();
  return ret;
}

char[] SAM_NAME_OUTBOUND_ALLOWZEROHOP() {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.SAM_NAME_OUTBOUND_ALLOWZEROHOP_get());
  return ret;
}

char[] SAM_NAME_OUTBOUND_IPRESTRICTION() {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.SAM_NAME_OUTBOUND_IPRESTRICTION_get());
  return ret;
}

int SAM_DEFAULT_OUTBOUND_IPRESTRICTION() {
  auto ret = i2psam_im.SAM_DEFAULT_OUTBOUND_IPRESTRICTION_get();
  return ret;
}

char[] SAM_NAME_OUTBOUND_PRIORITY() {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.SAM_NAME_OUTBOUND_PRIORITY_get());
  return ret;
}

int SOCKET_ERROR() {
  auto ret = i2psam_im.SOCKET_ERROR_get();
  return ret;
}

int MAX_PATH() {
  auto ret = i2psam_im.MAX_PATH_get();
  return ret;
}

int MSG_NOSIGNAL() {
  auto ret = i2psam_im.MSG_NOSIGNAL_get();
  return ret;
}

int PRIO_MAX() {
  auto ret = i2psam_im.PRIO_MAX_get();
  return ret;
}

int THREAD_PRIORITY_LOWEST() {
  auto ret = i2psam_im.THREAD_PRIORITY_LOWEST_get();
  return ret;
}

int THREAD_PRIORITY_BELOW_NORMAL() {
  auto ret = i2psam_im.THREAD_PRIORITY_BELOW_NORMAL_get();
  return ret;
}

int THREAD_PRIORITY_NORMAL() {
  auto ret = i2psam_im.THREAD_PRIORITY_NORMAL_get();
  return ret;
}

int THREAD_PRIORITY_ABOVE_NORMAL() {
  auto ret = i2psam_im.THREAD_PRIORITY_ABOVE_NORMAL_get();
  return ret;
}

size_t strnlen_int(char[] start, size_t max_len) {
  auto ret = i2psam_im.strnlen_int((start ? tango.stdc.stringz.toStringz(start) : null), max_len);
  return ret;
}

class i2psam_stream_settings {
  private void* swigCPtr;
  protected bool swigCMemOwn;

  public this(void* cObject, bool ownCObject) {
    swigCPtr = cObject;
    swigCMemOwn = ownCObject;
  }

  public static void* swigGetCPtr(typeof(this) obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin i2psam_im.SwigOperatorDefinitions;

  ~this() {
    dispose();
  }

  public void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          i2psam_im.delete_i2psam_stream_settings(cast(void*)swigCPtr);
        }
        swigCPtr = null;
      }
    }
  }

  public void samhost(char[] value) {
    i2psam_im.i2psam_stream_settings_samhost_set(cast(void*)swigCPtr, (value ? tango.stdc.stringz.toStringz(value) : null));
  }

  public char[] samhost() {
    char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.i2psam_stream_settings_samhost_get(cast(void*)swigCPtr));
    return ret;
  }

  public SWIGTYPE_p_uint16_t samport() {
    SWIGTYPE_p_uint16_t ret = new SWIGTYPE_p_uint16_t(i2psam_im.i2psam_stream_settings_samport_get(cast(void*)swigCPtr), true);
    return ret;
  }

  public void nickname(char[] value) {
    i2psam_im.i2psam_stream_settings_nickname_set(cast(void*)swigCPtr, (value ? tango.stdc.stringz.toStringz(value) : null));
  }

  public char[] nickname() {
    char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.i2psam_stream_settings_nickname_get(cast(void*)swigCPtr));
    return ret;
  }

  public void i2cp_opts(char[] value) {
    i2psam_im.i2psam_stream_settings_i2cp_opts_set(cast(void*)swigCPtr, (value ? tango.stdc.stringz.toStringz(value) : null));
  }

  public char[] i2cp_opts() {
    char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.i2psam_stream_settings_i2cp_opts_get(cast(void*)swigCPtr));
    return ret;
  }

  public void destination(char[] value) {
    i2psam_im.i2psam_stream_settings_destination_set(cast(void*)swigCPtr, (value ? tango.stdc.stringz.toStringz(value) : null));
  }

  public char[] destination() {
    char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.i2psam_stream_settings_destination_get(cast(void*)swigCPtr));
    return ret;
  }

  public this() {
    this(i2psam_im.new_i2psam_stream_settings(), true);
  }
}

SWIGTYPE_p_i2psam_stream_session i2psam_stream_session_new(i2psam_stream_settings arg0) {
  void* cPtr = i2psam_im.i2psam_stream_session_new(i2psam_stream_settings.swigGetCPtr(arg0));
  SWIGTYPE_p_i2psam_stream_session ret = (cPtr is null) ? null : new SWIGTYPE_p_i2psam_stream_session(cPtr, false);
  return ret;
}

void i2psam_stream_session_free(SWIGTYPE_p_i2psam_stream_session arg0) {
  i2psam_im.i2psam_stream_session_free(SWIGTYPE_p_i2psam_stream_session.swigGetCPtr(arg0));
}

char[] i2psam_get_samhost(SWIGTYPE_p_i2psam_stream_session arg0) {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.i2psam_get_samhost(SWIGTYPE_p_i2psam_stream_session.swigGetCPtr(arg0)));
  return ret;
}

SWIGTYPE_p_uint16_t i2psam_get_samport(SWIGTYPE_p_i2psam_stream_session arg0) {
  SWIGTYPE_p_uint16_t ret = new SWIGTYPE_p_uint16_t(i2psam_im.i2psam_get_samport(SWIGTYPE_p_i2psam_stream_session.swigGetCPtr(arg0)), true);
  return ret;
}

char[] i2psam_get_nickname(SWIGTYPE_p_i2psam_stream_session arg0) {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.i2psam_get_nickname(SWIGTYPE_p_i2psam_stream_session.swigGetCPtr(arg0)));
  return ret;
}

char[] i2psam_get_session_id(SWIGTYPE_p_i2psam_stream_session arg0) {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.i2psam_get_session_id(SWIGTYPE_p_i2psam_stream_session.swigGetCPtr(arg0)));
  return ret;
}

char[] i2psam_get_sam_min_version(SWIGTYPE_p_i2psam_stream_session arg0) {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.i2psam_get_sam_min_version(SWIGTYPE_p_i2psam_stream_session.swigGetCPtr(arg0)));
  return ret;
}

char[] i2psam_get_sam_max_version(SWIGTYPE_p_i2psam_stream_session arg0) {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.i2psam_get_sam_max_version(SWIGTYPE_p_i2psam_stream_session.swigGetCPtr(arg0)));
  return ret;
}

char[] i2psam_get_sam_version(SWIGTYPE_p_i2psam_stream_session arg0) {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.i2psam_get_sam_version(SWIGTYPE_p_i2psam_stream_session.swigGetCPtr(arg0)));
  return ret;
}

char[] i2psam_get_i2cp_options(SWIGTYPE_p_i2psam_stream_session arg0) {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.i2psam_get_i2cp_options(SWIGTYPE_p_i2psam_stream_session.swigGetCPtr(arg0)));
  return ret;
}

int i2psam_is_sick(SWIGTYPE_p_i2psam_stream_session arg0) {
  auto ret = i2psam_im.i2psam_is_sick(SWIGTYPE_p_i2psam_stream_session.swigGetCPtr(arg0));
  return ret;
}

SWIGTYPE_p_i2psam_socket i2psam_accept(SWIGTYPE_p_i2psam_stream_session arg0, int silent) {
  void* cPtr = i2psam_im.i2psam_accept(SWIGTYPE_p_i2psam_stream_session.swigGetCPtr(arg0), silent);
  SWIGTYPE_p_i2psam_socket ret = (cPtr is null) ? null : new SWIGTYPE_p_i2psam_socket(cPtr, false);
  return ret;
}

SWIGTYPE_p_i2psam_socket i2psam_connect(SWIGTYPE_p_i2psam_stream_session arg0, char[] destination, int silent) {
  void* cPtr = i2psam_im.i2psam_connect(SWIGTYPE_p_i2psam_stream_session.swigGetCPtr(arg0), (destination ? tango.stdc.stringz.toStringz(destination) : null), silent);
  SWIGTYPE_p_i2psam_socket ret = (cPtr is null) ? null : new SWIGTYPE_p_i2psam_socket(cPtr, false);
  return ret;
}

int i2psam_forward(SWIGTYPE_p_i2psam_stream_session arg0, char[] host, SWIGTYPE_p_uint16_t port, int silent) {
  auto ret = i2psam_im.i2psam_forward(SWIGTYPE_p_i2psam_stream_session.swigGetCPtr(arg0), (host ? tango.stdc.stringz.toStringz(host) : null), SWIGTYPE_p_uint16_t.swigGetCPtr(port), silent);
  if (i2psam_im.SwigPendingException.isPending) throw i2psam_im.SwigPendingException.retrieve();
  return ret;
}

char[] i2psam_namelookup(SWIGTYPE_p_i2psam_stream_session arg0, char[] name) {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.i2psam_namelookup(SWIGTYPE_p_i2psam_stream_session.swigGetCPtr(arg0), (name ? tango.stdc.stringz.toStringz(name) : null)));
  return ret;
}

SWIGTYPE_p_i2psam_destination i2psam_dest_generate(SWIGTYPE_p_i2psam_stream_session arg0) {
  void* cPtr = i2psam_im.i2psam_dest_generate(SWIGTYPE_p_i2psam_stream_session.swigGetCPtr(arg0));
  SWIGTYPE_p_i2psam_destination ret = (cPtr is null) ? null : new SWIGTYPE_p_i2psam_destination(cPtr, false);
  return ret;
}

void i2psam_stop_forwarding(SWIGTYPE_p_i2psam_stream_session arg0, char[] host, SWIGTYPE_p_uint16_t port) {
  i2psam_im.i2psam_stop_forwarding(SWIGTYPE_p_i2psam_stream_session.swigGetCPtr(arg0), (host ? tango.stdc.stringz.toStringz(host) : null), SWIGTYPE_p_uint16_t.swigGetCPtr(port));
  if (i2psam_im.SwigPendingException.isPending) throw i2psam_im.SwigPendingException.retrieve();
}

void i2psam_stop_forwarding_all(SWIGTYPE_p_i2psam_stream_session arg0) {
  i2psam_im.i2psam_stop_forwarding_all(SWIGTYPE_p_i2psam_stream_session.swigGetCPtr(arg0));
}

SWIGTYPE_p_i2psam_destination i2psam_get_my_destination(SWIGTYPE_p_i2psam_stream_session arg0) {
  void* cPtr = i2psam_im.i2psam_get_my_destination(SWIGTYPE_p_i2psam_stream_session.swigGetCPtr(arg0));
  SWIGTYPE_p_i2psam_destination ret = (cPtr is null) ? null : new SWIGTYPE_p_i2psam_destination(cPtr, false);
  return ret;
}

void i2psam_write(SWIGTYPE_p_i2psam_socket arg0, char[] data, size_t dlen) {
  i2psam_im.i2psam_write(SWIGTYPE_p_i2psam_socket.swigGetCPtr(arg0), (data ? tango.stdc.stringz.toStringz(data) : null), dlen);
}

char[] i2psam_read(SWIGTYPE_p_i2psam_socket arg0, size_t* dlen) {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.i2psam_read(SWIGTYPE_p_i2psam_socket.swigGetCPtr(arg0), cast(void*)dlen));
  return ret;
}

void i2psam_socket_close(SWIGTYPE_p_i2psam_socket arg0) {
  i2psam_im.i2psam_socket_close(SWIGTYPE_p_i2psam_socket.swigGetCPtr(arg0));
}

int i2psam_socket_is_ok(SWIGTYPE_p_i2psam_socket arg0) {
  auto ret = i2psam_im.i2psam_socket_is_ok(SWIGTYPE_p_i2psam_socket.swigGetCPtr(arg0));
  return ret;
}

void i2psam_socket_free(SWIGTYPE_p_i2psam_socket arg0) {
  i2psam_im.i2psam_socket_free(SWIGTYPE_p_i2psam_socket.swigGetCPtr(arg0));
}

char[] i2psam_destination_priv(SWIGTYPE_p_i2psam_destination arg0) {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.i2psam_destination_priv(SWIGTYPE_p_i2psam_destination.swigGetCPtr(arg0)));
  return ret;
}

char[] i2psam_destination_pub(SWIGTYPE_p_i2psam_destination arg0) {
  char[] ret = tango.stdc.stringz.fromStringz(i2psam_im.i2psam_destination_pub(SWIGTYPE_p_i2psam_destination.swigGetCPtr(arg0)));
  return ret;
}

void i2psam_destination_free(SWIGTYPE_p_i2psam_destination arg0) {
  i2psam_im.i2psam_destination_free(SWIGTYPE_p_i2psam_destination.swigGetCPtr(arg0));
}

class SWIGTYPE_p_i2psam_destination {
  private void* swigCPtr;

  public this(void* cObject, bool futureUse) {
    swigCPtr = cObject;
  }

  protected this() {
    swigCPtr = null;
  }

  public static void* swigGetCPtr(typeof(this) obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin i2psam_im.SwigOperatorDefinitions;
}

class SWIGTYPE_p_uint16_t {
  private void* swigCPtr;

  public this(void* cObject, bool futureUse) {
    swigCPtr = cObject;
  }

  protected this() {
    swigCPtr = null;
  }

  public static void* swigGetCPtr(typeof(this) obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin i2psam_im.SwigOperatorDefinitions;
}

class SWIGTYPE_p_i2psam_stream_session {
  private void* swigCPtr;

  public this(void* cObject, bool futureUse) {
    swigCPtr = cObject;
  }

  protected this() {
    swigCPtr = null;
  }

  public static void* swigGetCPtr(typeof(this) obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin i2psam_im.SwigOperatorDefinitions;
}

class SWIGTYPE_p_i2psam_socket {
  private void* swigCPtr;

  public this(void* cObject, bool futureUse) {
    swigCPtr = cObject;
  }

  protected this() {
    swigCPtr = null;
  }

  public static void* swigGetCPtr(typeof(this) obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin i2psam_im.SwigOperatorDefinitions;
}
