/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_I2PSAM_H
#define PHP_I2PSAM_H

extern zend_module_entry i2psam_module_entry;
#define phpext_i2psam_ptr &i2psam_module_entry

#ifdef PHP_WIN32
# define PHP_I2PSAM_API __declspec(dllexport)
#else
# define PHP_I2PSAM_API
#endif

ZEND_NAMED_FUNCTION(_wrap_strnlen_int);
ZEND_NAMED_FUNCTION(_wrap_i2psam_stream_settings_samhost_set);
ZEND_NAMED_FUNCTION(_wrap_i2psam_stream_settings_samhost_get);
ZEND_NAMED_FUNCTION(_wrap_i2psam_stream_settings_samport_get);
ZEND_NAMED_FUNCTION(_wrap_i2psam_stream_settings_nickname_set);
ZEND_NAMED_FUNCTION(_wrap_i2psam_stream_settings_nickname_get);
ZEND_NAMED_FUNCTION(_wrap_i2psam_stream_settings_i2cp_opts_set);
ZEND_NAMED_FUNCTION(_wrap_i2psam_stream_settings_i2cp_opts_get);
ZEND_NAMED_FUNCTION(_wrap_i2psam_stream_settings_destination_set);
ZEND_NAMED_FUNCTION(_wrap_i2psam_stream_settings_destination_get);
ZEND_NAMED_FUNCTION(_wrap_new_i2psam_stream_settings);
ZEND_NAMED_FUNCTION(_wrap_i2psam_stream_session_new);
ZEND_NAMED_FUNCTION(_wrap_i2psam_stream_session_free);
ZEND_NAMED_FUNCTION(_wrap_i2psam_get_samhost);
ZEND_NAMED_FUNCTION(_wrap_i2psam_get_samport);
ZEND_NAMED_FUNCTION(_wrap_i2psam_get_nickname);
ZEND_NAMED_FUNCTION(_wrap_i2psam_get_session_id);
ZEND_NAMED_FUNCTION(_wrap_i2psam_get_sam_min_version);
ZEND_NAMED_FUNCTION(_wrap_i2psam_get_sam_max_version);
ZEND_NAMED_FUNCTION(_wrap_i2psam_get_sam_version);
ZEND_NAMED_FUNCTION(_wrap_i2psam_get_i2cp_options);
ZEND_NAMED_FUNCTION(_wrap_i2psam_is_sick);
ZEND_NAMED_FUNCTION(_wrap_i2psam_accept);
ZEND_NAMED_FUNCTION(_wrap_i2psam_connect);
ZEND_NAMED_FUNCTION(_wrap_i2psam_forward);
ZEND_NAMED_FUNCTION(_wrap_i2psam_namelookup);
ZEND_NAMED_FUNCTION(_wrap_i2psam_dest_generate);
ZEND_NAMED_FUNCTION(_wrap_i2psam_stop_forwarding);
ZEND_NAMED_FUNCTION(_wrap_i2psam_stop_forwarding_all);
ZEND_NAMED_FUNCTION(_wrap_i2psam_get_my_destination);
ZEND_NAMED_FUNCTION(_wrap_i2psam_write);
ZEND_NAMED_FUNCTION(_wrap_i2psam_read);
ZEND_NAMED_FUNCTION(_wrap_i2psam_socket_close);
ZEND_NAMED_FUNCTION(_wrap_i2psam_socket_is_ok);
ZEND_NAMED_FUNCTION(_wrap_i2psam_socket_free);
ZEND_NAMED_FUNCTION(_wrap_i2psam_destination_priv);
ZEND_NAMED_FUNCTION(_wrap_i2psam_destination_pub);
ZEND_NAMED_FUNCTION(_wrap_i2psam_destination_free);
PHP_MINIT_FUNCTION(i2psam);

#endif /* PHP_I2PSAM_H */
