# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

##   Generated via the command line invocation:
##	 swig -r -outdir r i2psam.swigcxx


#                         srun.swg                            #
#
# This is the basic code that is needed at run time within R to
# provide and define the relevant classes.  It is included
# automatically in the generated code by copying the contents of
# srun.swg into the newly created binding code.


# This could be provided as a separate run-time library but this
# approach allows the code to be included directly into the
# generated bindings and so removes the need to have and install an
# additional library.  We may however end up with multiple copies of
# this and some confusion at run-time as to which class to use. This
# is an issue when we use NAMESPACES as we may need to export certain
# classes.

######################################################################

if(length(getClassDef("RSWIGStruct")) == 0) 
  setClass("RSWIGStruct", representation("VIRTUAL"))



if(length(getClassDef("ExternalReference")) == 0) 
# Should be virtual but this means it loses its slots currently
#representation("VIRTUAL")
  setClass("ExternalReference", representation( ref = "externalptr"))



if(length(getClassDef("NativeRoutinePointer")) == 0) 
  setClass("NativeRoutinePointer", 
              representation(parameterTypes = "character",
                             returnType = "character",
                             "VIRTUAL"), 
              contains = "ExternalReference")

if(length(getClassDef("CRoutinePointer")) == 0) 
  setClass("CRoutinePointer", contains = "NativeRoutinePointer")


if(length(getClassDef("EnumerationValue")) == 0) 
  setClass("EnumerationValue", contains = "integer")


if(!isGeneric("copyToR")) 
 setGeneric("copyToR",
            function(value, obj = new(gsub("Ref$", "", class(value)))) 
               standardGeneric("copyToR"
           ))

setGeneric("delete", function(obj) standardGeneric("delete"))


SWIG_createNewRef = 
function(className, ..., append = TRUE)
{
  f = get(paste("new", className, sep = "_"), mode = "function")

  f(...)
}

if(!isGeneric("copyToC")) 
 setGeneric("copyToC", 
             function(value, obj = SWIG_createNewRef(class(value)))
              standardGeneric("copyToC"
            ))


# 
defineEnumeration =
function(name, .values, where = topenv(parent.frame()), suffix = "Value")
{
   # Mirror the class definitions via the E analogous to .__C__
  defName = paste(".__E__", name, sep = "")
  delayedAssign(defName,  .values, assign.env = where)

  if(nchar(suffix))
    name = paste(name, suffix, sep = "")

  setClass(name, contains = "EnumerationValue", where = where)
}

enumToInteger <- function(name,type)
{
   if (is.character(name)) {
   ans <- as.integer(get(paste(".__E__", type, sep = ""))[name])
   if (is.na(ans)) {warning("enum not found ", name, " ", type)}
   ans
   } 
}

enumFromInteger =
function(i,type)
{
  itemlist <- get(paste(".__E__", type, sep=""))
  names(itemlist)[match(i, itemlist)]
}

coerceIfNotSubclass =
function(obj, type) 
{
    if(!is(obj, type)) {as(obj, type)} else obj
}


setClass("SWIGArray", representation(dims = "integer"), contains = "ExternalReference")

setMethod("length", "SWIGArray", function(x) x@dims[1])


defineEnumeration("SCopyReferences",
                   .values = c( "FALSE" = 0, "TRUE" = 1, "DEEP" = 2))

assert = 
function(condition, message = "")
{
  if(!condition)
    stop(message)

  TRUE
}


if(FALSE) {
print.SWIGFunction =
function(x, ...)
 {
 }
}


#######################################################################

R_SWIG_getCallbackFunctionStack =
function()
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_debug_getCallbackFunctionData")
}

R_SWIG_addCallbackFunctionStack =
function(fun, userData = NULL)
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_R_pushCallbackFunctionData", fun, userData)
}


#######################################################################



setClass('_p_i2psam_stream_settings', contains = 'ExternalReference')
setClass("i2psam_stream_settings",
    representation(
        samhost = "character",
        nickname = "character",
        i2cp_opts = "character",
        destination = "character"),
        contains = "RSWIGStruct")


# End class i2psam_stream_settings




setMethod('[', "ExternalReference",
function(x,i,j, ..., drop=TRUE) 
if (!is.null(x$"__getitem__")) 
sapply(i, function(n) x$"__getitem__"(i=as.integer(n-1))))

setMethod('[<-' , "ExternalReference",
function(x,i,j, ..., value) 
if (!is.null(x$"__setitem__")) {
sapply(1:length(i), function(n) 
x$"__setitem__"(i=as.integer(i[n]-1), x=value[n]))
x
})

setAs('ExternalReference', 'character',
function(from) {if (!is.null(from$"__str__")) from$"__str__"()})

suppressMessages(suppressWarnings(setMethod('print', 'ExternalReference',
function(x) {print(as(x, "character"))})))

# Start of strnlen_int

`strnlen_int` = function(start, max_len, .copy = FALSE)
{
  start = as(start, "character"); 
  max_len = as.integer(max_len);
  
  if(length(max_len) > 1) {
    warning("using only the first element of max_len");
  };
  
  ;.Call('R_swig_strnlen_int', start, max_len, as.logical(.copy), PACKAGE='i2psam');
  
}

attr(`strnlen_int`, 'returnType') = 'integer'
attr(`strnlen_int`, "inputTypes") = c('character', 'integer')
class(`strnlen_int`) = c("SWIGFunction", class('strnlen_int'))

# Start of i2psam_stream_settings_samhost_set

`i2psam_stream_settings_samhost_set` = function(self, s_samhost)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_samhost = as(s_samhost, "character"); 
  ;.Call('R_swig_i2psam_stream_settings_samhost_set', self, s_samhost, PACKAGE='i2psam');
  
}

attr(`i2psam_stream_settings_samhost_set`, 'returnType') = 'void'
attr(`i2psam_stream_settings_samhost_set`, "inputTypes") = c('_p_i2psam_stream_settings', 'character')
class(`i2psam_stream_settings_samhost_set`) = c("SWIGFunction", class('i2psam_stream_settings_samhost_set'))

# Start of i2psam_stream_settings_samhost_get

`i2psam_stream_settings_samhost_get` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_i2psam_stream_settings_samhost_get', self, PACKAGE='i2psam');
  
}

attr(`i2psam_stream_settings_samhost_get`, 'returnType') = 'character'
attr(`i2psam_stream_settings_samhost_get`, "inputTypes") = c('_p_i2psam_stream_settings')
class(`i2psam_stream_settings_samhost_get`) = c("SWIGFunction", class('i2psam_stream_settings_samhost_get'))

# Start of i2psam_stream_settings_samport_get

`i2psam_stream_settings_samport_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;ans = .Call('R_swig_i2psam_stream_settings_samport_get', self, as.logical(.copy), PACKAGE='i2psam');
  ans <- if (is.null(ans)) ans
  else new("_p_uint16_t", ref=ans);
  
  ans
  
}

attr(`i2psam_stream_settings_samport_get`, 'returnType') = '_p_uint16_t'
attr(`i2psam_stream_settings_samport_get`, "inputTypes") = c('_p_i2psam_stream_settings')
class(`i2psam_stream_settings_samport_get`) = c("SWIGFunction", class('i2psam_stream_settings_samport_get'))

# Start of i2psam_stream_settings_nickname_set

`i2psam_stream_settings_nickname_set` = function(self, s_nickname)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_nickname = as(s_nickname, "character"); 
  ;.Call('R_swig_i2psam_stream_settings_nickname_set', self, s_nickname, PACKAGE='i2psam');
  
}

attr(`i2psam_stream_settings_nickname_set`, 'returnType') = 'void'
attr(`i2psam_stream_settings_nickname_set`, "inputTypes") = c('_p_i2psam_stream_settings', 'character')
class(`i2psam_stream_settings_nickname_set`) = c("SWIGFunction", class('i2psam_stream_settings_nickname_set'))

# Start of i2psam_stream_settings_nickname_get

`i2psam_stream_settings_nickname_get` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_i2psam_stream_settings_nickname_get', self, PACKAGE='i2psam');
  
}

attr(`i2psam_stream_settings_nickname_get`, 'returnType') = 'character'
attr(`i2psam_stream_settings_nickname_get`, "inputTypes") = c('_p_i2psam_stream_settings')
class(`i2psam_stream_settings_nickname_get`) = c("SWIGFunction", class('i2psam_stream_settings_nickname_get'))

# Start of i2psam_stream_settings_i2cp_opts_set

`i2psam_stream_settings_i2cp_opts_set` = function(self, s_i2cp_opts)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_i2cp_opts = as(s_i2cp_opts, "character"); 
  ;.Call('R_swig_i2psam_stream_settings_i2cp_opts_set', self, s_i2cp_opts, PACKAGE='i2psam');
  
}

attr(`i2psam_stream_settings_i2cp_opts_set`, 'returnType') = 'void'
attr(`i2psam_stream_settings_i2cp_opts_set`, "inputTypes") = c('_p_i2psam_stream_settings', 'character')
class(`i2psam_stream_settings_i2cp_opts_set`) = c("SWIGFunction", class('i2psam_stream_settings_i2cp_opts_set'))

# Start of i2psam_stream_settings_i2cp_opts_get

`i2psam_stream_settings_i2cp_opts_get` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_i2psam_stream_settings_i2cp_opts_get', self, PACKAGE='i2psam');
  
}

attr(`i2psam_stream_settings_i2cp_opts_get`, 'returnType') = 'character'
attr(`i2psam_stream_settings_i2cp_opts_get`, "inputTypes") = c('_p_i2psam_stream_settings')
class(`i2psam_stream_settings_i2cp_opts_get`) = c("SWIGFunction", class('i2psam_stream_settings_i2cp_opts_get'))

# Start of i2psam_stream_settings_destination_set

`i2psam_stream_settings_destination_set` = function(self, s_destination)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_destination = as(s_destination, "character"); 
  ;.Call('R_swig_i2psam_stream_settings_destination_set', self, s_destination, PACKAGE='i2psam');
  
}

attr(`i2psam_stream_settings_destination_set`, 'returnType') = 'void'
attr(`i2psam_stream_settings_destination_set`, "inputTypes") = c('_p_i2psam_stream_settings', 'character')
class(`i2psam_stream_settings_destination_set`) = c("SWIGFunction", class('i2psam_stream_settings_destination_set'))

# Start of i2psam_stream_settings_destination_get

`i2psam_stream_settings_destination_get` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_i2psam_stream_settings_destination_get', self, PACKAGE='i2psam');
  
}

attr(`i2psam_stream_settings_destination_get`, 'returnType') = 'character'
attr(`i2psam_stream_settings_destination_get`, "inputTypes") = c('_p_i2psam_stream_settings')
class(`i2psam_stream_settings_destination_get`) = c("SWIGFunction", class('i2psam_stream_settings_destination_get'))

# Start of new_i2psam_stream_settings

`i2psam_stream_settings` = function(.copy = FALSE)
{
  ;ans = .Call('R_swig_new_i2psam_stream_settings', as.logical(.copy), PACKAGE='i2psam');
  ans <- if (is.null(ans)) ans
  else new("_p_i2psam_stream_settings", ref=ans);
  
  reg.finalizer(ans@ref, delete_i2psam_stream_settings)
  ans
  
}

attr(`i2psam_stream_settings`, 'returnType') = '_p_i2psam_stream_settings'
class(`i2psam_stream_settings`) = c("SWIGFunction", class('i2psam_stream_settings'))

# Start of delete_i2psam_stream_settings

`delete_i2psam_stream_settings` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_delete_i2psam_stream_settings', self, PACKAGE='i2psam');
  
}

attr(`delete_i2psam_stream_settings`, 'returnType') = 'void'
attr(`delete_i2psam_stream_settings`, "inputTypes") = c('_p_i2psam_stream_settings')
class(`delete_i2psam_stream_settings`) = c("SWIGFunction", class('delete_i2psam_stream_settings'))

# Start of accessor method for i2psam_stream_settings
setMethod('$', '_p_i2psam_stream_settings', function(x, name)

{
  accessorFuns = list('samhost' = i2psam_stream_settings_samhost_get, 'samport' = i2psam_stream_settings_samport_get, 'nickname' = i2psam_stream_settings_nickname_get, 'i2cp_opts' = i2psam_stream_settings_i2cp_opts_get, 'destination' = i2psam_stream_settings_destination_get);
  vaccessors = c('samhost', 'samport', 'nickname', 'i2cp_opts', 'destination');
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  if (is.na(match(name, vaccessors))) function(...){
    f(x, ...)
  } else f(x);
}


);
# end of accessor method for i2psam_stream_settings
# Start of accessor method for i2psam_stream_settings
setMethod('$<-', '_p_i2psam_stream_settings', function(x, name, value)

{
  accessorFuns = list('samhost' = i2psam_stream_settings_samhost_set, 'nickname' = i2psam_stream_settings_nickname_set, 'i2cp_opts' = i2psam_stream_settings_i2cp_opts_set, 'destination' = i2psam_stream_settings_destination_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
setMethod('[[<-', c('_p_i2psam_stream_settings', 'character'),function(x, i, j, ..., value)

{
  name = i;
  accessorFuns = list('samhost' = i2psam_stream_settings_samhost_set, 'nickname' = i2psam_stream_settings_nickname_set, 'i2cp_opts' = i2psam_stream_settings_i2cp_opts_set, 'destination' = i2psam_stream_settings_destination_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
# end of accessor method for i2psam_stream_settings
setMethod('delete', '_p_i2psam_stream_settings', function(obj) {delete_i2psam_stream_settings(obj)})
# Start definition of copy functions & methods for i2psam_stream_settings
CopyToR_i2psam_stream_settings = function(value, obj = new("i2psam_stream_settings"))
{
  obj@samhost = value$samhost;
  obj@nickname = value$nickname;
  obj@i2cp_opts = value$i2cp_opts;
  obj@destination = value$destination;
  obj;
}



CopyToC_i2psam_stream_settings = function(value, obj)
{
  obj$samhost = value@samhost;
  obj$nickname = value@nickname;
  obj$i2cp_opts = value@i2cp_opts;
  obj$destination = value@destination;
  obj
}



# Start definition of copy methods for i2psam_stream_settings
setMethod('copyToR', '_p_i2psam_stream_settings', CopyToR_i2psam_stream_settings);
setMethod('copyToC', 'i2psam_stream_settings', CopyToC_i2psam_stream_settings);

# End definition of copy methods for i2psam_stream_settings
# End definition of copy functions & methods for i2psam_stream_settings
# Start of i2psam_stream_session_new

`i2psam_stream_session_new` = function(s_arg1, .copy = FALSE)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  ;ans = .Call('R_swig_i2psam_stream_session_new', s_arg1, as.logical(.copy), PACKAGE='i2psam');
  ans <- if (is.null(ans)) ans
  else new("_p_i2psam_stream_session", ref=ans);
  
  ans
  
}

attr(`i2psam_stream_session_new`, 'returnType') = '_p_i2psam_stream_session'
attr(`i2psam_stream_session_new`, "inputTypes") = c('_p_i2psam_stream_settings')
class(`i2psam_stream_session_new`) = c("SWIGFunction", class('i2psam_stream_session_new'))

# Start of i2psam_stream_session_free

`i2psam_stream_session_free` = function(s_arg1)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  ;.Call('R_swig_i2psam_stream_session_free', s_arg1, PACKAGE='i2psam');
  
}

attr(`i2psam_stream_session_free`, 'returnType') = 'void'
attr(`i2psam_stream_session_free`, "inputTypes") = c('_p_i2psam_stream_session')
class(`i2psam_stream_session_free`) = c("SWIGFunction", class('i2psam_stream_session_free'))

# Start of i2psam_get_samhost

`i2psam_get_samhost` = function(s_arg1)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  ;.Call('R_swig_i2psam_get_samhost', s_arg1, PACKAGE='i2psam');
  
}

attr(`i2psam_get_samhost`, 'returnType') = 'character'
attr(`i2psam_get_samhost`, "inputTypes") = c('_p_i2psam_stream_session')
class(`i2psam_get_samhost`) = c("SWIGFunction", class('i2psam_get_samhost'))

# Start of i2psam_get_samport

`i2psam_get_samport` = function(s_arg1, .copy = FALSE)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  ;ans = .Call('R_swig_i2psam_get_samport', s_arg1, as.logical(.copy), PACKAGE='i2psam');
  ans <- if (is.null(ans)) ans
  else new("_p_uint16_t", ref=ans);
  
  ans
  
}

attr(`i2psam_get_samport`, 'returnType') = '_p_uint16_t'
attr(`i2psam_get_samport`, "inputTypes") = c('_p_i2psam_stream_session')
class(`i2psam_get_samport`) = c("SWIGFunction", class('i2psam_get_samport'))

# Start of i2psam_get_nickname

`i2psam_get_nickname` = function(s_arg1)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  ;.Call('R_swig_i2psam_get_nickname', s_arg1, PACKAGE='i2psam');
  
}

attr(`i2psam_get_nickname`, 'returnType') = 'character'
attr(`i2psam_get_nickname`, "inputTypes") = c('_p_i2psam_stream_session')
class(`i2psam_get_nickname`) = c("SWIGFunction", class('i2psam_get_nickname'))

# Start of i2psam_get_session_id

`i2psam_get_session_id` = function(s_arg1)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  ;.Call('R_swig_i2psam_get_session_id', s_arg1, PACKAGE='i2psam');
  
}

attr(`i2psam_get_session_id`, 'returnType') = 'character'
attr(`i2psam_get_session_id`, "inputTypes") = c('_p_i2psam_stream_session')
class(`i2psam_get_session_id`) = c("SWIGFunction", class('i2psam_get_session_id'))

# Start of i2psam_get_sam_min_version

`i2psam_get_sam_min_version` = function(s_arg1)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  ;.Call('R_swig_i2psam_get_sam_min_version', s_arg1, PACKAGE='i2psam');
  
}

attr(`i2psam_get_sam_min_version`, 'returnType') = 'character'
attr(`i2psam_get_sam_min_version`, "inputTypes") = c('_p_i2psam_stream_session')
class(`i2psam_get_sam_min_version`) = c("SWIGFunction", class('i2psam_get_sam_min_version'))

# Start of i2psam_get_sam_max_version

`i2psam_get_sam_max_version` = function(s_arg1)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  ;.Call('R_swig_i2psam_get_sam_max_version', s_arg1, PACKAGE='i2psam');
  
}

attr(`i2psam_get_sam_max_version`, 'returnType') = 'character'
attr(`i2psam_get_sam_max_version`, "inputTypes") = c('_p_i2psam_stream_session')
class(`i2psam_get_sam_max_version`) = c("SWIGFunction", class('i2psam_get_sam_max_version'))

# Start of i2psam_get_sam_version

`i2psam_get_sam_version` = function(s_arg1)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  ;.Call('R_swig_i2psam_get_sam_version', s_arg1, PACKAGE='i2psam');
  
}

attr(`i2psam_get_sam_version`, 'returnType') = 'character'
attr(`i2psam_get_sam_version`, "inputTypes") = c('_p_i2psam_stream_session')
class(`i2psam_get_sam_version`) = c("SWIGFunction", class('i2psam_get_sam_version'))

# Start of i2psam_get_i2cp_options

`i2psam_get_i2cp_options` = function(s_arg1)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  ;.Call('R_swig_i2psam_get_i2cp_options', s_arg1, PACKAGE='i2psam');
  
}

attr(`i2psam_get_i2cp_options`, 'returnType') = 'character'
attr(`i2psam_get_i2cp_options`, "inputTypes") = c('_p_i2psam_stream_session')
class(`i2psam_get_i2cp_options`) = c("SWIGFunction", class('i2psam_get_i2cp_options'))

# Start of i2psam_is_sick

`i2psam_is_sick` = function(s_arg1, .copy = FALSE)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  ;.Call('R_swig_i2psam_is_sick', s_arg1, as.logical(.copy), PACKAGE='i2psam');
  
}

attr(`i2psam_is_sick`, 'returnType') = 'integer'
attr(`i2psam_is_sick`, "inputTypes") = c('_p_i2psam_stream_session')
class(`i2psam_is_sick`) = c("SWIGFunction", class('i2psam_is_sick'))

# Start of i2psam_accept

`i2psam_accept` = function(s_arg1, silent, .copy = FALSE)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  silent = as.integer(silent);
  
  if(length(silent) > 1) {
    warning("using only the first element of silent");
  };
  
  ;ans = .Call('R_swig_i2psam_accept', s_arg1, silent, as.logical(.copy), PACKAGE='i2psam');
  ans <- if (is.null(ans)) ans
  else new("_p_i2psam_socket", ref=ans);
  
  ans
  
}

attr(`i2psam_accept`, 'returnType') = '_p_i2psam_socket'
attr(`i2psam_accept`, "inputTypes") = c('_p_i2psam_stream_session', 'integer')
class(`i2psam_accept`) = c("SWIGFunction", class('i2psam_accept'))

# Start of i2psam_connect

`i2psam_connect` = function(s_arg1, destination, silent, .copy = FALSE)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  destination = as(destination, "character"); 
  silent = as.integer(silent);
  
  if(length(silent) > 1) {
    warning("using only the first element of silent");
  };
  
  ;ans = .Call('R_swig_i2psam_connect', s_arg1, destination, silent, as.logical(.copy), PACKAGE='i2psam');
  ans <- if (is.null(ans)) ans
  else new("_p_i2psam_socket", ref=ans);
  
  ans
  
}

attr(`i2psam_connect`, 'returnType') = '_p_i2psam_socket'
attr(`i2psam_connect`, "inputTypes") = c('_p_i2psam_stream_session', 'character', 'integer')
class(`i2psam_connect`) = c("SWIGFunction", class('i2psam_connect'))

# Start of i2psam_forward

`i2psam_forward` = function(s_arg1, host, port, silent, .copy = FALSE)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  host = as(host, "character"); 
  if (inherits(port, "ExternalReference")) port = slot(port,"ref") 
  silent = as.integer(silent);
  
  if(length(silent) > 1) {
    warning("using only the first element of silent");
  };
  
  ;.Call('R_swig_i2psam_forward', s_arg1, host, port, silent, as.logical(.copy), PACKAGE='i2psam');
  
}

attr(`i2psam_forward`, 'returnType') = 'integer'
attr(`i2psam_forward`, "inputTypes") = c('_p_i2psam_stream_session', 'character', '_p_uint16_t', 'integer')
class(`i2psam_forward`) = c("SWIGFunction", class('i2psam_forward'))

# Start of i2psam_namelookup

`i2psam_namelookup` = function(s_arg1, name)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  name = as(name, "character"); 
  ;.Call('R_swig_i2psam_namelookup', s_arg1, name, PACKAGE='i2psam');
  
}

attr(`i2psam_namelookup`, 'returnType') = 'character'
attr(`i2psam_namelookup`, "inputTypes") = c('_p_i2psam_stream_session', 'character')
class(`i2psam_namelookup`) = c("SWIGFunction", class('i2psam_namelookup'))

# Start of i2psam_dest_generate

`i2psam_dest_generate` = function(s_arg1, .copy = FALSE)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  ;ans = .Call('R_swig_i2psam_dest_generate', s_arg1, as.logical(.copy), PACKAGE='i2psam');
  ans <- if (is.null(ans)) ans
  else new("_p_i2psam_destination", ref=ans);
  
  ans
  
}

attr(`i2psam_dest_generate`, 'returnType') = '_p_i2psam_destination'
attr(`i2psam_dest_generate`, "inputTypes") = c('_p_i2psam_stream_session')
class(`i2psam_dest_generate`) = c("SWIGFunction", class('i2psam_dest_generate'))

# Start of i2psam_stop_forwarding

`i2psam_stop_forwarding` = function(s_arg1, host, port)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  host = as(host, "character"); 
  if (inherits(port, "ExternalReference")) port = slot(port,"ref") 
  ;.Call('R_swig_i2psam_stop_forwarding', s_arg1, host, port, PACKAGE='i2psam');
  
}

attr(`i2psam_stop_forwarding`, 'returnType') = 'void'
attr(`i2psam_stop_forwarding`, "inputTypes") = c('_p_i2psam_stream_session', 'character', '_p_uint16_t')
class(`i2psam_stop_forwarding`) = c("SWIGFunction", class('i2psam_stop_forwarding'))

# Start of i2psam_stop_forwarding_all

`i2psam_stop_forwarding_all` = function(s_arg1)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  ;.Call('R_swig_i2psam_stop_forwarding_all', s_arg1, PACKAGE='i2psam');
  
}

attr(`i2psam_stop_forwarding_all`, 'returnType') = 'void'
attr(`i2psam_stop_forwarding_all`, "inputTypes") = c('_p_i2psam_stream_session')
class(`i2psam_stop_forwarding_all`) = c("SWIGFunction", class('i2psam_stop_forwarding_all'))

# Start of i2psam_get_my_destination

`i2psam_get_my_destination` = function(s_arg1, .copy = FALSE)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  ;ans = .Call('R_swig_i2psam_get_my_destination', s_arg1, as.logical(.copy), PACKAGE='i2psam');
  ans <- if (is.null(ans)) ans
  else new("_p_i2psam_destination", ref=ans);
  
  ans
  
}

attr(`i2psam_get_my_destination`, 'returnType') = '_p_i2psam_destination'
attr(`i2psam_get_my_destination`, "inputTypes") = c('_p_i2psam_stream_session')
class(`i2psam_get_my_destination`) = c("SWIGFunction", class('i2psam_get_my_destination'))

# Start of i2psam_write

`i2psam_write` = function(s_arg1, data, dlen)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  data = as(data, "character"); 
  dlen = as.integer(dlen);
  
  if(length(dlen) > 1) {
    warning("using only the first element of dlen");
  };
  
  ;.Call('R_swig_i2psam_write', s_arg1, data, dlen, PACKAGE='i2psam');
  
}

attr(`i2psam_write`, 'returnType') = 'void'
attr(`i2psam_write`, "inputTypes") = c('_p_i2psam_socket', 'character', 'integer')
class(`i2psam_write`) = c("SWIGFunction", class('i2psam_write'))

# Start of i2psam_read

`i2psam_read` = function(s_arg1, dlen)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  dlen = as.integer(dlen);
  ;.Call('R_swig_i2psam_read', s_arg1, dlen, PACKAGE='i2psam');
  
}

attr(`i2psam_read`, 'returnType') = 'character'
attr(`i2psam_read`, "inputTypes") = c('_p_i2psam_socket', 'integer')
class(`i2psam_read`) = c("SWIGFunction", class('i2psam_read'))

# Start of i2psam_socket_close

`i2psam_socket_close` = function(s_arg1)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  ;.Call('R_swig_i2psam_socket_close', s_arg1, PACKAGE='i2psam');
  
}

attr(`i2psam_socket_close`, 'returnType') = 'void'
attr(`i2psam_socket_close`, "inputTypes") = c('_p_i2psam_socket')
class(`i2psam_socket_close`) = c("SWIGFunction", class('i2psam_socket_close'))

# Start of i2psam_socket_is_ok

`i2psam_socket_is_ok` = function(s_arg1, .copy = FALSE)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  ;.Call('R_swig_i2psam_socket_is_ok', s_arg1, as.logical(.copy), PACKAGE='i2psam');
  
}

attr(`i2psam_socket_is_ok`, 'returnType') = 'integer'
attr(`i2psam_socket_is_ok`, "inputTypes") = c('_p_i2psam_socket')
class(`i2psam_socket_is_ok`) = c("SWIGFunction", class('i2psam_socket_is_ok'))

# Start of i2psam_socket_free

`i2psam_socket_free` = function(s_arg1)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  ;.Call('R_swig_i2psam_socket_free', s_arg1, PACKAGE='i2psam');
  
}

attr(`i2psam_socket_free`, 'returnType') = 'void'
attr(`i2psam_socket_free`, "inputTypes") = c('_p_i2psam_socket')
class(`i2psam_socket_free`) = c("SWIGFunction", class('i2psam_socket_free'))

# Start of i2psam_destination_priv

`i2psam_destination_priv` = function(s_arg1)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  ;.Call('R_swig_i2psam_destination_priv', s_arg1, PACKAGE='i2psam');
  
}

attr(`i2psam_destination_priv`, 'returnType') = 'character'
attr(`i2psam_destination_priv`, "inputTypes") = c('_p_i2psam_destination')
class(`i2psam_destination_priv`) = c("SWIGFunction", class('i2psam_destination_priv'))

# Start of i2psam_destination_pub

`i2psam_destination_pub` = function(s_arg1)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  ;.Call('R_swig_i2psam_destination_pub', s_arg1, PACKAGE='i2psam');
  
}

attr(`i2psam_destination_pub`, 'returnType') = 'character'
attr(`i2psam_destination_pub`, "inputTypes") = c('_p_i2psam_destination')
class(`i2psam_destination_pub`) = c("SWIGFunction", class('i2psam_destination_pub'))

# Start of i2psam_destination_free

`i2psam_destination_free` = function(s_arg1)
{
  if (inherits(s_arg1, "ExternalReference")) s_arg1 = slot(s_arg1,"ref") 
  ;.Call('R_swig_i2psam_destination_free', s_arg1, PACKAGE='i2psam');
  
}

attr(`i2psam_destination_free`, 'returnType') = 'void'
attr(`i2psam_destination_free`, "inputTypes") = c('_p_i2psam_destination')
class(`i2psam_destination_free`) = c("SWIGFunction", class('i2psam_destination_free'))



